/*
 * @(#)Constants.java     1.00 2020/02/14
 *
 * This software is free for use.
 */
package ua.testing.view.entity;

public interface Constants {

    String MESSAGE_PROFIT_ = "MESSAGE_PROFIT";
    String MESSAGE_PROFIT_REPLENISHMENT = "MESSAGE_PROFIT_REPLENISHMENT";
    String MESSAGE_PROFIT_EARLY_WITHDRAWAL = "MESSAGE_PROFIT_EARLY_WITHDRAWAL";
    String MESSAGE_PROFIT_REPLENISHMENT_EARLY_WITHDRAWAL = "MESSAGE_PROFIT_REPLENISHMENT_EARLY_WITHDRAWAL";

    // use in deposit toString()
    String DEPOSIT_PROGRAMM_TO_STRING = "DEPOSIT_PROGRAMM_TO_STRING";
    String BANK_TO_STRING = "BANK_TO_STRING";
    String PROFIT_TO_STRING = "PROFIT_TO_STRING";
    String REPLANISHMENT_TO_STRING = "REPLANISHMENT_TO_STRING";
    String EARLY_WITHDRAWAL_TO_STRING = "EARLY_WITHDRAWAL_TO_STRING";
    String CLOSED_BRACKET = "CLOSED_BRACKET";

}
